### ISSUE TITLE
Add Instagram data to the Datalake

### ISSUE THREAD

**Issue by leonardo-brickabode** [Jellyfish-Insights/andromeda#26]
- [x] I have searched the [issues](https://github.com/Marketing-Automation-Systems/jellyfish/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Jellyfish is a data lake that gathers statistical data from different social media. Adding the Instagram statistical data to the data lake will aggregate more value to this project.

## Motivation 🔦

Instagram is one of the most popular social media right now, with more than 1 billion users [using it every month](https://blog.hootsuite.com/instagram-statistics/). Having the ability to fetch data from Instagram and storing it on the data lake will aggregate a lot more value to this project.

**Comment by leonardo-brickabode** [comment]
Instagram was enabled on #76 but we have to see the following issue, to consider this feature done:
{
   "error": {
      "message": "Invalid parameter",
      "type": "OAuthException",
      "code": 100,
      "error_data": {
         "blame_field_specs": [
            [
               ""
            ]
         ]
      },
      "error_subcode": 2108006,
      "is_transient": false,
      "error_user_title": "Media Posted Before Business Account Conversion",
      "error_user_msg": "The media was posted before the most recent time that the user's account was converted to a business account from a personal account.",
      "fbtrace_id": "Aw555CUdh1111WBKeXSWE1"
   }
}

**Comment by moraesvic** [comment]
Closing because the project context changed too much since then
