### ISSUE TITLE
Migrate functions doesn't handle exceptions

### ISSUE THREAD

**Issue by lucaslovato** [Jellyfish-Insights/andromeda#60]
- [X] I have searched the [issues](https://github.com/Marketing-Automation-Systems/jellyfish/issues/) of this repository and believe that this is not a duplicate.

## Describe the bug 🐛

Verifications are always needed on the project, with this on the file `MigrateCommand.cs` when the program calls the functions `` and `` after them the project is just printing `success` so a verification for exceptions on this functions is requested.

## To Reproduce 😯

1. Go to andromeda/Andromeda.ConsoleApp/Commands/MigrateCommand.cs
2. Scroll down to lines `31` and `39`
3. See that functions `MigrateDataLake()` and `MigrateFacebook()` doesn't handle exceptions

## Expected behavior 🤔

We expect that database functions are prepared to handle exceptions.

## Your environment
- OS: Ubuntu 18.04

**Comment by moraesvic** [comment]
Closing because the project context changed too much since then
