### ISSUE TITLE
Improving Jobs logs messages

### ISSUE THREAD

**Issue by lucaslovato** [Jellyfish-Insights/andromeda#62]
- [x] I have searched the [issues](https://github.com/Marketing-Automation-Systems/jellyfish/issues) of this repository and believe that this is not a duplicate.

## Summary 💡
This feature request intends to improve the log's message when Jobs starts. The idea is to print what credentials were found and also what credentials weren't found. After, a new log printing what Jobs will start to fetch.

## Motivation 🔦
The motivation for this feature request is to the user understands better what it's being fetched or not from APIs in a better format.

**Comment by moraesvic** [comment]
Closing because the project context changed too much since then
